apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30800
    port: 3000
    protocol: TCP
    targetPort: web
  selector:
    prometheus: grafana
